linters:
  fast: false
  enable:
    - misspell
    - prealloc
    - revive
    - unconvert
    - unparam
    - errorlint
    - gocritic
    # - gosec
linters-settings:
  revive:
    enableAllRules: true
    rules:
      - name: var-naming
        arguments:
          - ["ID"]
  gocritic:
    enabled-tags:
      - performance
      - diagnostic
      - style
      - opinionated
      - experimental
    disabled-checks:
      - singleCaseSwitch
      - deferInLoop
      - hugeParam
      - unnamedResult
issues:
  exclude-rules:
    - linters:
        - revive
      text: ALL_CAPS
  max-issues-per-linter: 0

run:
  tests: false
  skip-dirs:
    - helios-chain/modules/peggy/testpeggy
    - helios-chain/modules/exchange/testexchange
    - helios-chain/modules/exchange/client/testutil
