# Dockerfile.tests
FROM golang:1.22.4-bookworm as builder
RUN apt install git gcc make libc-dev

# Set working directory
WORKDIR /apps

# Copy source code
COPY . .

# Install dependencies
RUN go mod tidy

# Run tests
CMD ["go", "test", "./helios-chain/...", "-tags=test", "-cover", "-v"]