// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: helios/chronos/v1/cron.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Defines when messages will be executed in the block
type ExecutionStage int32

const (
	ExecutionStage_EXECUTION_STAGE_END_BLOCKER   ExecutionStage = 0
	ExecutionStage_EXECUTION_STAGE_BEGIN_BLOCKER ExecutionStage = 1
)

var ExecutionStage_name = map[int32]string{
	0: "EXECUTION_STAGE_END_BLOCKER",
	1: "EXECUTION_STAGE_BEGIN_BLOCKER",
}

var ExecutionStage_value = map[string]int32{
	"EXECUTION_STAGE_END_BLOCKER":   0,
	"EXECUTION_STAGE_BEGIN_BLOCKER": 1,
}

func (x ExecutionStage) String() string {
	return proto.EnumName(ExecutionStage_name, int32(x))
}

func (ExecutionStage) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_40f0621bb4e9e794, []int{0}
}

// Cron for autonomous EVM smart-contract execution
type Cron struct {
	Id                 uint64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address            string         `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	OwnerAddress       string         `protobuf:"bytes,3,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	ContractAddress    string         `protobuf:"bytes,4,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	AbiJson            string         `protobuf:"bytes,5,opt,name=abi_json,json=abiJson,proto3" json:"abi_json,omitempty"`
	MethodName         string         `protobuf:"bytes,6,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	Params             []string       `protobuf:"bytes,7,rep,name=params,proto3" json:"params,omitempty"`
	Frequency          uint64         `protobuf:"varint,8,opt,name=frequency,proto3" json:"frequency,omitempty"`
	NextExecutionBlock uint64         `protobuf:"varint,9,opt,name=next_execution_block,json=nextExecutionBlock,proto3" json:"next_execution_block,omitempty"`
	ExpirationBlock    uint64         `protobuf:"varint,10,opt,name=expiration_block,json=expirationBlock,proto3" json:"expiration_block,omitempty"`
	ExecutionStage     ExecutionStage `protobuf:"varint,11,opt,name=execution_stage,json=executionStage,proto3,enum=helios.chronos.v1.ExecutionStage" json:"execution_stage,omitempty"`
	GasLimit           uint64         `protobuf:"varint,12,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	MaxGasPrice        uint64         `protobuf:"varint,13,opt,name=max_gas_price,json=maxGasPrice,proto3" json:"max_gas_price,omitempty"`
}

func (m *Cron) Reset()         { *m = Cron{} }
func (m *Cron) String() string { return proto.CompactTextString(m) }
func (*Cron) ProtoMessage()    {}
func (*Cron) Descriptor() ([]byte, []int) {
	return fileDescriptor_40f0621bb4e9e794, []int{0}
}
func (m *Cron) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Cron) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Cron.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Cron) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cron.Merge(m, src)
}
func (m *Cron) XXX_Size() int {
	return m.Size()
}
func (m *Cron) XXX_DiscardUnknown() {
	xxx_messageInfo_Cron.DiscardUnknown(m)
}

var xxx_messageInfo_Cron proto.InternalMessageInfo

func (m *Cron) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Cron) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Cron) GetOwnerAddress() string {
	if m != nil {
		return m.OwnerAddress
	}
	return ""
}

func (m *Cron) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *Cron) GetAbiJson() string {
	if m != nil {
		return m.AbiJson
	}
	return ""
}

func (m *Cron) GetMethodName() string {
	if m != nil {
		return m.MethodName
	}
	return ""
}

func (m *Cron) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *Cron) GetFrequency() uint64 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

func (m *Cron) GetNextExecutionBlock() uint64 {
	if m != nil {
		return m.NextExecutionBlock
	}
	return 0
}

func (m *Cron) GetExpirationBlock() uint64 {
	if m != nil {
		return m.ExpirationBlock
	}
	return 0
}

func (m *Cron) GetExecutionStage() ExecutionStage {
	if m != nil {
		return m.ExecutionStage
	}
	return ExecutionStage_EXECUTION_STAGE_END_BLOCKER
}

func (m *Cron) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *Cron) GetMaxGasPrice() uint64 {
	if m != nil {
		return m.MaxGasPrice
	}
	return 0
}

func init() {
	proto.RegisterEnum("helios.chronos.v1.ExecutionStage", ExecutionStage_name, ExecutionStage_value)
	proto.RegisterType((*Cron)(nil), "helios.chronos.v1.Cron")
}

func init() { proto.RegisterFile("helios/chronos/v1/cron.proto", fileDescriptor_40f0621bb4e9e794) }

var fileDescriptor_40f0621bb4e9e794 = []byte{
	// 467 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xc1, 0x6e, 0xd3, 0x30,
	0x18, 0xc7, 0x9b, 0xb6, 0x74, 0x8d, 0xbb, 0xb6, 0xc3, 0x9a, 0x90, 0x61, 0x23, 0xeb, 0xc6, 0x25,
	0x20, 0x91, 0x30, 0x78, 0x82, 0xa5, 0x44, 0xd5, 0xc6, 0xd4, 0xa1, 0xac, 0x48, 0x88, 0x8b, 0xe5,
	0x26, 0x26, 0x35, 0x34, 0x76, 0xb0, 0xb3, 0x91, 0xbd, 0x05, 0x8f, 0xc5, 0x71, 0x47, 0x0e, 0x1c,
	0x50, 0xfb, 0x22, 0x28, 0x4e, 0xd3, 0x32, 0x76, 0xf3, 0xf7, 0xff, 0xfd, 0x94, 0xbf, 0x3e, 0xe5,
	0x03, 0xfb, 0x33, 0x3a, 0x67, 0x42, 0xb9, 0xe1, 0x4c, 0x0a, 0x2e, 0x94, 0x7b, 0x7d, 0xec, 0x86,
	0x52, 0x70, 0x27, 0x95, 0x22, 0x13, 0xf0, 0x61, 0x49, 0x9d, 0x15, 0x75, 0xae, 0x8f, 0x9f, 0xec,
	0xc6, 0x22, 0x16, 0x9a, 0xba, 0xc5, 0xab, 0x14, 0x8f, 0x7e, 0x37, 0x40, 0x73, 0x28, 0x05, 0x87,
	0x3d, 0x50, 0x67, 0x11, 0x32, 0x06, 0x86, 0xdd, 0x0c, 0xea, 0x2c, 0x82, 0x08, 0x6c, 0x91, 0x28,
	0x92, 0x54, 0x29, 0x54, 0x1f, 0x18, 0xb6, 0x19, 0x54, 0x23, 0x7c, 0x06, 0xba, 0xe2, 0x3b, 0xa7,
	0x12, 0x57, 0xbc, 0xa1, 0xf9, 0xb6, 0x0e, 0x4f, 0x56, 0xd2, 0x73, 0xb0, 0x13, 0x0a, 0x9e, 0x49,
	0x12, 0x66, 0x6b, 0xaf, 0xa9, 0xbd, 0x7e, 0x95, 0x57, 0xea, 0x63, 0xd0, 0x26, 0x53, 0x86, 0xbf,
	0x28, 0xc1, 0xd1, 0x83, 0x55, 0xd5, 0x94, 0x9d, 0x29, 0xc1, 0xe1, 0x01, 0xe8, 0x24, 0x34, 0x9b,
	0x89, 0x08, 0x73, 0x92, 0x50, 0xd4, 0xd2, 0x14, 0x94, 0xd1, 0x98, 0x24, 0x14, 0x3e, 0x02, 0xad,
	0x94, 0x48, 0x92, 0x28, 0xb4, 0x35, 0x68, 0xd8, 0x66, 0xb0, 0x9a, 0xe0, 0x3e, 0x30, 0x3f, 0x4b,
	0xfa, 0xed, 0x8a, 0xf2, 0xf0, 0x06, 0xb5, 0xf5, 0x52, 0x9b, 0x00, 0xbe, 0x02, 0xbb, 0x9c, 0xe6,
	0x19, 0xa6, 0x39, 0x0d, 0xaf, 0x32, 0x26, 0x38, 0x9e, 0xce, 0x45, 0xf8, 0x15, 0x99, 0x5a, 0x84,
	0x05, 0xf3, 0x2b, 0xe4, 0x15, 0xa4, 0x58, 0x87, 0xe6, 0x29, 0x93, 0xe4, 0x1f, 0x1b, 0x68, 0xbb,
	0xbf, 0xc9, 0x4b, 0xf5, 0x0c, 0xf4, 0x37, 0xdf, 0x55, 0x19, 0x89, 0x29, 0xea, 0x0c, 0x0c, 0xbb,
	0xf7, 0xfa, 0xd0, 0xb9, 0xf7, 0x53, 0x9c, 0x75, 0xcd, 0x65, 0x21, 0x06, 0x3d, 0x7a, 0x67, 0x86,
	0x7b, 0xc0, 0x8c, 0x89, 0xc2, 0x73, 0x96, 0xb0, 0x0c, 0x6d, 0xeb, 0xbe, 0x76, 0x4c, 0xd4, 0x79,
	0x31, 0xc3, 0x23, 0xd0, 0x4d, 0x48, 0x8e, 0x0b, 0x21, 0x95, 0x2c, 0xa4, 0xa8, 0xab, 0x85, 0x4e,
	0x42, 0xf2, 0x11, 0x51, 0xef, 0x8b, 0xe8, 0xc5, 0x04, 0xf4, 0xee, 0x56, 0xc0, 0x03, 0xb0, 0xe7,
	0x7f, 0xf4, 0x87, 0x1f, 0x26, 0xa7, 0x17, 0x63, 0x7c, 0x39, 0x39, 0x19, 0xf9, 0xd8, 0x1f, 0xbf,
	0xc5, 0xde, 0xf9, 0xc5, 0xf0, 0x9d, 0x1f, 0xec, 0xd4, 0xe0, 0x21, 0x78, 0xfa, 0xbf, 0xe0, 0xf9,
	0xa3, 0xd3, 0xf1, 0x5a, 0x31, 0x3c, 0xef, 0xe7, 0xc2, 0x32, 0x6e, 0x17, 0x96, 0xf1, 0x67, 0x61,
	0x19, 0x3f, 0x96, 0x56, 0xed, 0x76, 0x69, 0xd5, 0x7e, 0x2d, 0xad, 0xda, 0x27, 0xbb, 0x5c, 0xf1,
	0x65, 0x28, 0x24, 0x75, 0xab, 0xf7, 0x8c, 0x30, 0xee, 0xe6, 0xeb, 0x4b, 0xcd, 0x6e, 0x52, 0xaa,
	0xa6, 0x2d, 0x7d, 0x7f, 0x6f, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x1c, 0xdb, 0x2f, 0x60, 0xc8,
	0x02, 0x00, 0x00,
}

func (m *Cron) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Cron) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Cron) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxGasPrice != 0 {
		i = encodeVarintCron(dAtA, i, uint64(m.MaxGasPrice))
		i--
		dAtA[i] = 0x68
	}
	if m.GasLimit != 0 {
		i = encodeVarintCron(dAtA, i, uint64(m.GasLimit))
		i--
		dAtA[i] = 0x60
	}
	if m.ExecutionStage != 0 {
		i = encodeVarintCron(dAtA, i, uint64(m.ExecutionStage))
		i--
		dAtA[i] = 0x58
	}
	if m.ExpirationBlock != 0 {
		i = encodeVarintCron(dAtA, i, uint64(m.ExpirationBlock))
		i--
		dAtA[i] = 0x50
	}
	if m.NextExecutionBlock != 0 {
		i = encodeVarintCron(dAtA, i, uint64(m.NextExecutionBlock))
		i--
		dAtA[i] = 0x48
	}
	if m.Frequency != 0 {
		i = encodeVarintCron(dAtA, i, uint64(m.Frequency))
		i--
		dAtA[i] = 0x40
	}
	if len(m.Params) > 0 {
		for iNdEx := len(m.Params) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Params[iNdEx])
			copy(dAtA[i:], m.Params[iNdEx])
			i = encodeVarintCron(dAtA, i, uint64(len(m.Params[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.MethodName) > 0 {
		i -= len(m.MethodName)
		copy(dAtA[i:], m.MethodName)
		i = encodeVarintCron(dAtA, i, uint64(len(m.MethodName)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.AbiJson) > 0 {
		i -= len(m.AbiJson)
		copy(dAtA[i:], m.AbiJson)
		i = encodeVarintCron(dAtA, i, uint64(len(m.AbiJson)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintCron(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.OwnerAddress) > 0 {
		i -= len(m.OwnerAddress)
		copy(dAtA[i:], m.OwnerAddress)
		i = encodeVarintCron(dAtA, i, uint64(len(m.OwnerAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintCron(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintCron(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintCron(dAtA []byte, offset int, v uint64) int {
	offset -= sovCron(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Cron) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovCron(uint64(m.Id))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovCron(uint64(l))
	}
	l = len(m.OwnerAddress)
	if l > 0 {
		n += 1 + l + sovCron(uint64(l))
	}
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovCron(uint64(l))
	}
	l = len(m.AbiJson)
	if l > 0 {
		n += 1 + l + sovCron(uint64(l))
	}
	l = len(m.MethodName)
	if l > 0 {
		n += 1 + l + sovCron(uint64(l))
	}
	if len(m.Params) > 0 {
		for _, s := range m.Params {
			l = len(s)
			n += 1 + l + sovCron(uint64(l))
		}
	}
	if m.Frequency != 0 {
		n += 1 + sovCron(uint64(m.Frequency))
	}
	if m.NextExecutionBlock != 0 {
		n += 1 + sovCron(uint64(m.NextExecutionBlock))
	}
	if m.ExpirationBlock != 0 {
		n += 1 + sovCron(uint64(m.ExpirationBlock))
	}
	if m.ExecutionStage != 0 {
		n += 1 + sovCron(uint64(m.ExecutionStage))
	}
	if m.GasLimit != 0 {
		n += 1 + sovCron(uint64(m.GasLimit))
	}
	if m.MaxGasPrice != 0 {
		n += 1 + sovCron(uint64(m.MaxGasPrice))
	}
	return n
}

func sovCron(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCron(x uint64) (n int) {
	return sovCron(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Cron) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCron
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Cron: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Cron: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCron
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCron
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCron
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCron
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCron
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCron
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCron
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCron
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCron
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCron
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AbiJson", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCron
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCron
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCron
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AbiJson = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MethodName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCron
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCron
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCron
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MethodName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCron
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCron
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCron
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Params = append(m.Params, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Frequency", wireType)
			}
			m.Frequency = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCron
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Frequency |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextExecutionBlock", wireType)
			}
			m.NextExecutionBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCron
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextExecutionBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpirationBlock", wireType)
			}
			m.ExpirationBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCron
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpirationBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecutionStage", wireType)
			}
			m.ExecutionStage = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCron
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExecutionStage |= ExecutionStage(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasLimit", wireType)
			}
			m.GasLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCron
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GasLimit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxGasPrice", wireType)
			}
			m.MaxGasPrice = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCron
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxGasPrice |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCron(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCron
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCron(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCron
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCron
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCron
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCron
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCron
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCron
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCron        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCron          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCron = fmt.Errorf("proto: unexpected end of group")
)
