// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: helios/chronos/v1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Defines the parameters for the cron module.
type Params struct {
	// Limit of schedules executed in one block
	Limit uint64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Maximum number of scheduled calls allowed per wallet
	MaxScheduledCallsPerWallet uint64 `protobuf:"varint,2,opt,name=max_scheduled_calls_per_wallet,json=maxScheduledCallsPerWallet,proto3" json:"max_scheduled_calls_per_wallet,omitempty"`
	// Minimum gas fee multiplier to safely estimate gas (e.g., "1.2")
	MinimumGasFeeMultiplier string `protobuf:"bytes,3,opt,name=minimum_gas_fee_multiplier,json=minimumGasFeeMultiplier,proto3" json:"minimum_gas_fee_multiplier,omitempty"`
	// Global maximum allowed gas price for cron executions (optional default value)
	GlobalMaxGasPrice string `protobuf:"bytes,4,opt,name=global_max_gas_price,json=globalMaxGasPrice,proto3" json:"global_max_gas_price,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd175cea699159aa, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Params) GetMaxScheduledCallsPerWallet() uint64 {
	if m != nil {
		return m.MaxScheduledCallsPerWallet
	}
	return 0
}

func (m *Params) GetMinimumGasFeeMultiplier() string {
	if m != nil {
		return m.MinimumGasFeeMultiplier
	}
	return ""
}

func (m *Params) GetGlobalMaxGasPrice() string {
	if m != nil {
		return m.GlobalMaxGasPrice
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "helios.chronos.v1.Params")
}

func init() { proto.RegisterFile("helios/chronos/v1/params.proto", fileDescriptor_cd175cea699159aa) }

var fileDescriptor_cd175cea699159aa = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0xb1, 0x4a, 0x33, 0x41,
	0x14, 0x85, 0x77, 0xfe, 0x3f, 0x06, 0x9c, 0x2e, 0x4b, 0xc0, 0x25, 0xc5, 0x18, 0xac, 0xd2, 0x98,
	0x21, 0xd8, 0x69, 0x17, 0xc1, 0x54, 0x81, 0x10, 0x0b, 0xc1, 0x66, 0xb8, 0xd9, 0x5c, 0x77, 0x07,
	0x66, 0x32, 0xc3, 0xcc, 0x26, 0xae, 0x6f, 0x61, 0x69, 0xe9, 0xe3, 0x58, 0xa6, 0x12, 0x4b, 0xd9,
	0x7d, 0x11, 0xd9, 0xd9, 0x24, 0xdd, 0xb9, 0x7c, 0xdf, 0x81, 0xcb, 0xa1, 0x2c, 0x47, 0x25, 0x8d,
	0xe7, 0x69, 0xee, 0xcc, 0xc6, 0x78, 0xbe, 0x9b, 0x70, 0x0b, 0x0e, 0xb4, 0x1f, 0x5b, 0x67, 0x0a,
	0x13, 0xf7, 0x5a, 0x3e, 0x3e, 0xf0, 0xf1, 0x6e, 0x32, 0xe8, 0x67, 0x26, 0x33, 0x81, 0xf2, 0x26,
	0xb5, 0xe2, 0xd5, 0x37, 0xa1, 0xdd, 0x45, 0x68, 0xc6, 0x7d, 0x7a, 0xa6, 0xa4, 0x96, 0x45, 0x42,
	0x86, 0x64, 0xd4, 0x59, 0xb6, 0x47, 0x3c, 0xa5, 0x4c, 0x43, 0x29, 0x7c, 0x9a, 0xe3, 0x7a, 0xab,
	0x70, 0x2d, 0x52, 0x50, 0xca, 0x0b, 0x8b, 0x4e, 0xbc, 0x82, 0x52, 0x58, 0x24, 0xff, 0x82, 0x3e,
	0xd0, 0x50, 0x3e, 0x1e, 0xa5, 0xfb, 0xc6, 0x59, 0xa0, 0x7b, 0x0a, 0x46, 0x7c, 0x47, 0x07, 0x5a,
	0x6e, 0xa4, 0xde, 0x6a, 0x91, 0x81, 0x17, 0x2f, 0x88, 0x42, 0x6f, 0x55, 0x21, 0xad, 0x92, 0xe8,
	0x92, 0xff, 0x43, 0x32, 0x3a, 0x5f, 0x5e, 0x1c, 0x8c, 0x19, 0xf8, 0x07, 0xc4, 0xf9, 0x09, 0xc7,
	0x9c, 0xf6, 0x33, 0x65, 0x56, 0xa0, 0x44, 0xf3, 0x47, 0xd3, 0xb7, 0x4e, 0xa6, 0x98, 0x74, 0x42,
	0xad, 0xd7, 0xb2, 0x39, 0x94, 0x33, 0xf0, 0x8b, 0x06, 0xdc, 0x76, 0x3e, 0x3e, 0x2f, 0xa3, 0xe9,
	0xf4, 0xab, 0x62, 0x64, 0x5f, 0x31, 0xf2, 0x5b, 0x31, 0xf2, 0x5e, 0xb3, 0x68, 0x5f, 0xb3, 0xe8,
	0xa7, 0x66, 0xd1, 0xf3, 0xa8, 0xdd, 0xe6, 0x3a, 0x35, 0x0e, 0xf9, 0x31, 0xe7, 0x20, 0x37, 0xbc,
	0x3c, 0xed, 0x59, 0xbc, 0x59, 0xf4, 0xab, 0x6e, 0xd8, 0xe8, 0xe6, 0x2f, 0x00, 0x00, 0xff, 0xff,
	0xb2, 0x6e, 0x6c, 0x58, 0x6e, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.GlobalMaxGasPrice) > 0 {
		i -= len(m.GlobalMaxGasPrice)
		copy(dAtA[i:], m.GlobalMaxGasPrice)
		i = encodeVarintParams(dAtA, i, uint64(len(m.GlobalMaxGasPrice)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.MinimumGasFeeMultiplier) > 0 {
		i -= len(m.MinimumGasFeeMultiplier)
		copy(dAtA[i:], m.MinimumGasFeeMultiplier)
		i = encodeVarintParams(dAtA, i, uint64(len(m.MinimumGasFeeMultiplier)))
		i--
		dAtA[i] = 0x1a
	}
	if m.MaxScheduledCallsPerWallet != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxScheduledCallsPerWallet))
		i--
		dAtA[i] = 0x10
	}
	if m.Limit != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.Limit))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Limit != 0 {
		n += 1 + sovParams(uint64(m.Limit))
	}
	if m.MaxScheduledCallsPerWallet != 0 {
		n += 1 + sovParams(uint64(m.MaxScheduledCallsPerWallet))
	}
	l = len(m.MinimumGasFeeMultiplier)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.GlobalMaxGasPrice)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			m.Limit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Limit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxScheduledCallsPerWallet", wireType)
			}
			m.MaxScheduledCallsPerWallet = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxScheduledCallsPerWallet |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinimumGasFeeMultiplier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinimumGasFeeMultiplier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GlobalMaxGasPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GlobalMaxGasPrice = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
